### ISSUE TITLE
Heat benchmark tests with Jetson

### ISSUE THREAD

**Issue by CyonixC** [SOAR-UWU/UWU-Blobfish#10]

**Comment by Interpause** [comment]
For CPU: https://forums.developer.nvidia.com/t/cpu-gpu-stress-test-on-nx/129257/3
^^ `sudo apt install stress`, `stress --cpu 6`

For GPU: https://forums.developer.nvidia.com/t/cpu-gpu-stress-test-on-nx/129257/9
